### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-developer-tools#32]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

To be prepared for the december release of PHP 8.0, this repository has some additional TODOs to be tested against the new major version.

In order to make this repository compatible, one has to follow these steps:

- [ ] Modify `composer.json` to provide support for PHP 8.0 by adding the constraint `~8.0.0`
- [ ] Modify `composer.json` to drop support for PHP less than 7.3
- [ ] Modify `composer.json` to implement phpunit 9.3 which supports PHP 7.3+
- [ ] Modify `.travis.yml` to ignore platform requirements when installing composer dependencies (simply add `--ignore-platform-reqs` to `COMPOSER_ARGS` env variable)
- [ ] Modify `.travis.yml` to add PHP 8.0 to the matrix (*NOTE*: Do not allow failures as PHP 8.0 has a feature freeze since 2020-08-04!)
- [ ] Modify source code in case there are incompatibilities with PHP 8.0

**Comment by Gounlaf** [comment]
Depends on theses issues:
- [x] laminas/laminas-eventmanager (https://github.com/laminas/laminas-eventmanager/pull/10)
- [ ] laminas/laminas-modulemanager ( ? )
- [ ] laminas/laminas-mvc (https://github.com/laminas/laminas-mvc/issues/66)
- [ ] laminas/laminas-servicemanager (https://github.com/laminas/laminas-servicemanager/issues/55)
- [x] laminas/laminas-stdlib (https://github.com/laminas/laminas-stdlib/issues/1)
- [ ] laminas/laminas-view (https://github.com/laminas/laminas-view/issues/57)
- [x] laminas/laminas-zendframework-bridge ( ? )

**Comment by boesing** [comment]
@Gounlaf It should be possible to install all dependencies with `--ignore-platform-reqs` even if they do not directly support PHP 8.0.
The goal of this issue should be that everything is fixed for PHP 8.0 in this library. If other dependencies are not yet compatible with PHP 8.0 should not be that kind of problem (unless PHP 8.0 refuses to execute phpunit due to some circumstances).
But thanks for pointing this out :-)

**Comment by Gounlaf** [comment]
@boesing should type hinting be added on method returns? I don't know if it's considered as a BC Break =/

**Comment by boesing** [comment]
> @boesing should type hinting be added on method returns? I don't know if it's considered as a BC Break =/

It is a BC break. I've written detailed feedback - please focus on the minimum. I like the additions but we should do one enhancement per PR to give better feedback in CHANGELOG *and* to better triage every request 👍
